### ISSUE TITLE
uLogger no connection

### ISSUE THREAD

**Issue by 098714** [tinuzz/wp-plugin-trackserver#31] opened 2021-02-13 16:00 UTC
Hi, uLogger doesnt seem to connect to trackserver:

PHP 7.3 + MySQL 5.7
Wordpress 5.6.1
Trackserver 4.3.2
uLogger 3.5
Host: https://username:password@fschn.org/trackserver (htaccess username & password)
User: wordpress username
password: wordpress password

also no connection when htaccess and wordfence are deactivated, and host url accordingly adjusted. i also tried NextTrack app, but also no luck there. I get Http code 404, 403 & 401 errors. 

Not sure if I should try a different app or if i'm missing something in the setup.

thanks very much & best

**Comment by tinuzz** [comment] 2021-04-07 19:33
Hi,

I'm very sorry for the late reply. Somehow I missed this issue.

Trackserver 4.3.2, the current version on Wordpress.org, does not support uLogger. uLogger support was introduced shortly after the latest release. After that, I started to work on a rewrite of large parts of the plugin, which has prevented me from doing a release for a long time.

So, for uLogger support, you need to download the plugin from Github and install it manually.

I am back at Trackserver development, trying to get a release of v5.0 done, but it will take some time.

Best regards,
Martijn.

**Comment by tinuzz** [comment] 2021-04-07 20:20
Assuming the problem is the Trackserver version, I'm closing this. Feel free to re-open if you feel differently.

Martijn.

**Closed by tinuzz** 2021-04-07 20:20 UTC
